### ISSUE TITLE
cannot import name 'NavigationDrawer'

### ISSUE THREAD

**Issue by alexvhr** [HeaTTheatR/DemoKivyContacts#2]
Traceback (most recent call last):
  File "D:/TEMP/DemoKivyContacts/main.py", line 48, in main
    from program import Program  # основной класс программы
  File "D:\TEMP\DemoKivyContacts\program.py", line 25, in <module>
    from kivymd.navigationdrawer import NavigationDrawer
ImportError: cannot import name 'NavigationDrawer'

**Comment by HeaTTheatR** [comment]
Дело в том, что KivyMD находится в альфа версии, автор постоянно улучшает данную библиотеку, за что ему огромное спасибо. Данный проект написан с использованием более старой версии KivyMD, отсюда досадные ошибки.

**Comment by alexvhr** [comment]
Да, там радикально поменялись названия классов. Извините за наглость, а у вас нет актуального примера с KivyMD? Я пробежался по всем вашим публикациям на Хабре, выкачал все ваши демки, но ни одна не запускается под разными предлогами. (python 3.4). И ещё - удавалось ли вам собрать написанное на Python 3 kivy-приложение под андройд? Или надо делать строго на Py2? Дело в том, что я уже год бьюсь с киви (в свободное время, разумеется) и постоянно какие-то суровые проблемы.

**Comment by HeaTTheatR** [comment]
Подождите еще с месяц... Я обновлю репозиторий KivyIssues. Это будет
полноценное приложение, работающее так же быстро, как и нативное! В
нем вы сможете посмотреть исходные тексты.

Просто я уже пол года без своей рабочей станции, пишу прямо на
планшете в текстовых редакторах, тестирую с помощью KivyLauncher прямо
на девайсе программу, которая использует API ВКонтакте БЕЗ возможности
выйти в Интернет (китайский планшет). К тому же у меня всего один час
времени в сутки на разработку.

Приложение почти готово. Оно будет снабжено видео, статьей на Хабре
(тоже в процессе). Никаких проблем с Kivy никогда не встречал при
написании приложений в том числе и коммерческих.

Дождитесь...

03.05.2017, alexvhr<notifications@github.com> написал(а):
